// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ByID(arg1:number):Promise<models.Hero>;

export function ByShortName(arg1:string):Promise<models.Hero>;

export function GetFavorites():Promise<Record<number, Array<number>>>;

export function GetHeroes():Promise<Array<models.Hero>>;

export function GetSetting(arg1:string):Promise<string>;

export function PortraitsBaseURL():Promise<string>;

export function SetFavorites(arg1:number,arg2:Array<number>):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function Update(arg1:Array<models.Hero>):Promise<void>;
